# https://docs.netlify.com/configure-builds/file-based-configuration/#sample-file

[build]
  base = "/"
  publish = "dist/"
  command = "npm run build"

[[headers]]
  for = "/*"

  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Content-Security-Policy = "frame-ancestors https://www.facebook.com"

    cache-control = '''
	  max-age=0,
	  no-cache,
	  no-store,
	  must-revalidate'''